### ISSUE TITLE
Crash when trying to move top server up in the list

### ISSUE THREAD

**Issue by NielsPilgaard** [BisectStudios/BisectHostingServerIntegrationMenu#1]
[BH Menu 1.16.5 v1.1](https://www.curseforge.com/minecraft/mc-mods/bisecthosting-server-integration-menu-forge/files/3670354) 

This might've been fixed in 1.2, but it's hard to tell without it being in the changelog / issues 😅 

### Describe your issue.

Game crashes when moving a server in the list up when its the first server in the list.
Above the server entry is the server hoster advert.

Steps to reproduce:
1. Go to Multiplayer
2. Add a server
3. Move it up util its the first real server and second entry in the list
4. Move it up again

### Crash Report

https://paste.ee/p/hKDlv

### Latest Log

https://paste.ee/p/s5EUI

**Comment by Quarris** [comment]
Should be fixed in 1.2, yes

**Comment by NielsPilgaard** [comment]
Oh hi Quarris 😄 cool, thanks!
