### ISSUE TITLE
1.12.2 button translation missing

### ISSUE THREAD

**Issue by kreezxil** [BisectStudios/BisectHostingServerIntegrationMenu#10]
![image](https://github.com/BisectStudios/BisectHostingServerIntegrationMenu/assets/3880072/a9fdb2b7-bcc7-49b1-84bb-afc567f3e291)

**Comment by BisectStudios** [comment]
Bug fixed and uploaded has a hotfix on 1.12.2 Forge CF / Modrinth Page. It may take 24 hours for Curseforges approved. Thank you for contribution! :)
