### ISSUE TITLE
Update for 1.20.4 [Fabric]?

### ISSUE THREAD

**Issue by seriousfreezing** [BisectStudios/BisectHostingServerIntegrationMenu#12]

**Comment by BisectStudios** [comment]
@seriousfreezing Thank you for reporting this! We were able to reproduce the issue and our team is working on it asap! :)

**Comment by BisectStudios** [comment]
Added: https://www.curseforge.com/minecraft/mc-mods/bisecthosting-server-integration-menu-fabric/files/5251513
