### ISSUE TITLE
Directory of outdated textures

### ISSUE THREAD

**Issue by seriousfreezing** [BisectStudios/BisectHostingServerIntegrationMenu#13]
![image](https://github.com/BisectStudios/BisectHostingServerIntegrationMenu/assets/66693072/f9988acc-2b29-471b-9082-7de58e910b22)

1.20.4 has seen changes to the texture paths and their structure, but the mod still has its old structure.

**Comment by GabrielOlvH** [comment]
This has been fixed, thank you for reporting!
