### ISSUE TITLE
List of servers not visible with FancyMenu

### ISSUE THREAD

**Issue by seriousfreezing** [BisectStudios/BisectHostingServerIntegrationMenu#15]
I don't know if this only happens with FancyMenu, but it does happen.
You add a server to the multiplayer screen and it doesn't appear at all, you can interact with it but it's invisible.

**Comment by GabrielOlvH** [comment]
Hey, if you're still having this issue, could you please provide more information such as mod list and minecraft version?

**Comment by seriousfreezing** [comment]
I was on version 1.20.6 along with the latest versions of the mods. And it was fixed just by removing Bisect Hosting

**Comment by jakey1995abc** [comment]
I am having the same issue right now on 1.21 (fabric) without fancymenu or any other mods like that installed. Disabling bisect hosting mod fixed the issue for me also.
Here's my mod list:
![image](https://github.com/BisectStudios/BisectHostingServerIntegrationMenu/assets/7613005/1c4e834b-4768-4b2d-aa08-68a7c42b8474)

**Comment by GabrielOlvH** [comment]
Hey, sorry for the delay, can you provide a latest.log file? This looks like some mod incompatibility we'll need to fix. You can check this to find your logs if you need: 
https://www.bisecthosting.com/clients/index.php?rp=/knowledgebase/213/How-to-find-Minecraft-Java-client-logs.html

**Comment by seriousfreezing** [comment]
I've run several tests and it seems there's no longer this bug. I recreated the modpack mentioned before by jakey1995abc, and I remade it in my used modpack and no bug. If this bug returns, I will reopen it
