### ISSUE TITLE
[1.18.1] Crash when clicking BH button in top server list

### ISSUE THREAD

**Issue by ImAK9** [BisectStudios/BisectHostingServerIntegrationMenu#2]
https://aofpaste.com/atalebaqiv.yaml

**Comment by Quarris** [comment]
Which button is that and on which screen?

**Comment by ImAK9** [comment]
Screen name is in the log.

Screen name: com.bisecthosting.mods.bhmenu.screens.BHOrderScreen

Crashes when pressing BisectHosting button in server list.

**Comment by ImAK9** [comment]
v1.2 works as expected. v1.3 dosen’t

**Comment by Quarris** [comment]
Can't seem to reproduce it at all. What servers are displayed on your multiplayer screen, do you have more than just the server banner?

**Comment by ImAK9** [comment]
I ship 3 servers by default.
https://github.com/TeamAOF/All-of-Fabric-5/blob/main/config/builtinservers.json

**Comment by Quarris** [comment]
Can't seem to find the issue. Currently trying to load it with just fabric and the mod, using the same fabric api version and everything looks fine. I'll look into it tomorrow but I'm afraid it might be a mod compatibility with one of the hundreds of mods in there O.o

Is this a public modpack I can download and try?

![image](https://user-images.githubusercontent.com/6171764/161603538-0188f7d3-0a07-4a92-a6bb-01131ff9a0d3.png)

**Comment by ImAK9** [comment]
By all means, grab it here: https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5

**Comment by ImAK9** [comment]
I’ll see if I can track it down when on PC, let me know if you find something yourself.

**Comment by Quarris** [comment]
Sorry for such a late reply. I'm trying to look at the issue so I installed AoF5 - 1.18.2 on CF and it seems to have v1.3 and works fine. Does the issue still persists?

**Comment by ImAK9** [comment]
It's still an issue, change order of servers and click button.

https://aofpaste.com/sonuvopura.yaml

**Comment by ImAK9** [comment]
This could by all means be a compat issue with the [Builtinservers](https://www.curseforge.com/minecraft/mc-mods/builtin-servers) mod.

**Comment by Quarris** [comment]
I'm trying to figure out how to reproduce this issue.
I'm testing this on AOF5 v1.2.2 with mod v1.17.1-1.18.2-1.3 and it seems to work. Are you doing something different to this?
https://gyazo.com/04f8e4f3d01f57b65d9ec9b73c3d35de

**Comment by ImAK9** [comment]
Could you try manually adding a server with IP “localhost” or whatever on top of the already included ones.

**Comment by Quarris** [comment]
I've manually added localhost and moved them into every position and it still doesn't give me anything.
Let me try to update the pack and see, are you able to maybe show me a gif of how you made it crash?

**Comment by ImAK9** [comment]
> I've manually added localhost and moved them into every position and it still doesn't give me anything.
> Let me try to update the pack and see, are you able to maybe show me a gif of how you made it crash?

Will do as soon as I’m home. Also gonna try a couple fresh installs as my dev instance is different in a couple ways.

**Comment by Quarris** [comment]
Assuming this is fixed. Please re-open if the issue persists
