### ISSUE TITLE
crash when clicking on bhmenu in server list on 1.17.1

### ISSUE THREAD

**Issue by kreezxil** [BisectStudios/BisectHostingServerIntegrationMenu#3]
crash report: https://pastebin.com/NP2NUcpj

Minecraft: 1.17.1
Forge: 37.1.1

**Comment by kreezxil** [comment]
Works flawlessly on Forge 37.0.127. Problem starts with 37.1.0. The major class change causes issue apparently.

**Comment by Quarris** [comment]
Sorry for the delayed response.

Does the issue still persist? No issues when launching with just the mod on my end for either of the forge versions specified, and using v1.3 for the mod. I do see that there are more mods in this so it might be a conflict with some other mod. If the issue still persist could you send me the modpack zip on Discord (Quarris in BH Discord) so I can test it on that please.

**Comment by kreezxil** [comment]
you guys released an update shortly after I posted that, so I'd say it's
fixed. if it causes issue again, I will post that. :)
