### ISSUE TITLE
[1.19.2] Crash on startup

### ISSUE THREAD

**Issue by NielsPilgaard** [BisectStudios/BisectHostingServerIntegrationMenu#4]
BH Server Integration Menu causes an early crash on startup on Minecraft 1.19.2, with `Forge-1.19.2-43.0.19`

https://gist.github.com/NielsPilgaard/36ca789455a45bb97e77fe86b4f7ced3

**Comment by Quarris** [comment]
Oh snap, sorry we have the file ready but it hasn't been uploaded yet. We will get this done today!

**Comment by NielsPilgaard** [comment]
Thank you kindly 😊

**Comment by NielsPilgaard** [comment]
Did you perhaps forget about this? 😄

**Comment by Quarris** [comment]
I didn't, we have a weird thing with who upload files and stuff so I'm trying to get the file uploaded by someone who can. I'm gonna hopefully get an ability to upload files myself as well so next time it won't take this long!

**Comment by NielsPilgaard** [comment]
Ah okay 👍

**Comment by Quarris** [comment]
Alright I've uploaded the file to Curseforge, it's processing. Apologies for the delay!

**Comment by NielsPilgaard** [comment]
No worries, thanks!
