### ISSUE TITLE
Update to Forge & Fabric 1.19.4?

### ISSUE THREAD

**Issue by Atten007** [BisectStudios/BisectHostingServerIntegrationMenu#6]
Hello,

I want to add my Pokémon modpack when I'm releasing it for 1.19.4 to BisectHosting and I want to use this mod there. Unfortunately, it isn't currently available, so I wanted to ask you: Is it possible to upgrade this mod to 1.19.4?

Greetings,
Atten 😊

**Comment by BisectStudios** [comment]
We have updated the mod on Modrinth and Curseforge for version 1.19.4 and 1.20.1
