### ISSUE TITLE
First image in Modrinth description is too large - image size 136 megapixels, limit 71 megapixels

### ISSUE THREAD

**Issue by James103** [BisectStudios/BisectHostingServerIntegrationMenu#7]
When a user visits the Modrinth page for this mod, one of the banner images at the top of the description fails to load.

The reason given by the cache service Modrinth uses to serve images is:
`{"status":"error","code":404,"message":"Input image exceeds pixel limit. Width x height should be less than 71000000"}`

Direct link to failing image: https://www.bisecthosting.com/images/CF/BHMenu/BH_BHMENU_Header-Combined.png

Image size: 19507 x 7015, totalling 136.8 million pixels.

Workaround: Downscale the banner image by a factor of 2 and replace the original image with the downsampled image, which should fit within the image size limit.

**Comment by BisectStudios** [comment]
Good catch! We will get that fixed asap!

**Comment by BisectStudios** [comment]
Resolved. Image size reduce! Thanks again :)

**Comment by BisectStudios** [comment]
Closing
