### ISSUE TITLE
Mod not compatible with Forge 1.20.1-47.0.50

### ISSUE THREAD

**Issue by Mikeatron-User** [BisectStudios/BisectHostingServerIntegrationMenu#9]
**Information**
MC version: 1.20.1
Forge Version: 47.0.50
Only Bisect Mod Installed

**How to Recreate**

1. Create a Forge 1.20.1-47.0.50 instance.
2. Add this Mod..
3. Load into main menu.
4. Open multiplayer menu.

**Crash Log:**
https://gist.github.com/Mikeatron-User/dde05f1ed47b8d727f693146ee06ff93

**Comment by BisectStudios** [comment]
Hi Mikeatron! Our devs are actively working on a hot fix. Thank you for letting us know

**Comment by BisectStudios** [comment]
Hotfix is uploaded to Curseforge and Modrinth. Thank you again for bring this to our attention!

**Comment by BisectStudios** [comment]
Closing out.

**Comment by Mikeatron-User** [comment]
Thank you for the fast work! Great job :)
